version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build: ./PedidoAPI
    container_name: pedido_api
    ports:
      - "5000:80"
    depends_on:
      - mongo
      - rabbitmq

  consumer:
    build: ./PedidoConsumer
    container_name: pedido_consumer
    depends_on:
      - mongo
      - rabbitmq
    restart: always
    environment:
      - RABBITMQ_HOST=rabbitmq

volumes:
  mongo_data:
